"""Change user sessions

Revision ID: 110f14cc6f39
Revises: 320142725e82
Create Date: 2021-01-21 13:32:16.209987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "110f14cc6f39"
down_revision = "320142725e82"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sections", sa.Column("mode", sa.String(), nullable=True))
    op.add_column("sections", sa.Column("num_tracking", sa.Integer(), nullable=False, server_default="0"))

    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column("update_token")
        batch_op.drop_column("session_expiration")
        batch_op.drop_column("device_token")
        batch_op.drop_column("session_token")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("session_token", sa.VARCHAR(), nullable=False, server_default=""))
    op.add_column("users", sa.Column("device_token", sa.VARCHAR(), nullable=True))
    op.add_column("users", sa.Column("session_expiration", sa.DATETIME(), nullable=False, server_default=""))
    op.add_column("users", sa.Column("update_token", sa.VARCHAR(), nullable=False, server_default=""))

    with op.batch_alter_table("sections") as batch_op:
        batch_op.drop_column("num_tracking")
        batch_op.drop_column("mode")
    # ### end Alembic commands ###
