"""Add semesters

Revision ID: 320142725e82
Revises: c8591a7abce5
Create Date: 2020-04-21 01:49:07.098188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "320142725e82"
down_revision = "c8591a7abce5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "semesters",
        sa.Column("current_semester", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("current_semester"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("semesters")
    # ### end Alembic commands ###
