"""Update session

Revision ID: 3cfb8cf58e98
Revises: 110f14cc6f39
Create Date: 2021-04-04 01:26:03.892507

"""
from alembic import op
from datetime import datetime
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cfb8cf58e98'
down_revision = '110f14cc6f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column('last_used', sa.DateTime(), nullable=False, server_default=str(datetime.now())))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions") as batch_op:
        batch_op.drop_column("last_used")
    # ### end Alembic commands ###
