"""Initial migration

Revision ID: 6ce1a6f069ff
Revises:
Create Date: 2020-03-04 17:23:44.459614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6ce1a6f069ff"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_code", sa.String(), nullable=False),
        sa.Column("course_num", sa.Integer(), nullable=False),
        sa.Column("search_string", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.Integer(), nullable=False),
        sa.Column("session_token", sa.String(), nullable=False),
        sa.Column("session_expiration", sa.DateTime(), nullable=False),
        sa.Column("update_token", sa.String(), nullable=False),
        sa.Column("is_ios", sa.Boolean(), nullable=True),
        sa.Column("device_token", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("session_token"),
        sa.UniqueConstraint("update_token"),
    )
    op.create_table(
        "sections",
        sa.Column("catalog_num", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"],),
        sa.PrimaryKeyConstraint("catalog_num"),
    )
    op.create_table(
        "users_to_sections",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("catalog_num", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["catalog_num"], ["sections.catalog_num"],),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_to_sections")
    op.drop_table("sections")
    op.drop_table("users")
    op.drop_table("courses")
    # ### end Alembic commands ###
